server:
  port: 8002

spring:
  application:
    name: cfbo-cloud-movie-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
#      defaultZone: http://root:1@peer1:9001/eureka,http://root:1@peer2:9002/eureka
      defaultZone: http://root:1@peer1:9001/eureka

info:
  app:
    name: cfbo-cloud-movie-service
    encoding: UTF-8
    java:
      source: 1.8.0_211
      target: 1.8.0_211