server:
  port: 8001
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: cfbo-cloud-user-service

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

info:
  app:
    name: cfbo-cloud-user-service
    encoding: UTF-8
    java:
      source: 1.8.0_211
      target: 1.8.0_211

eureka:
  instance:
    prefer-ip-address: true
#    metadata-map:  【有问题，在另外项目中拿不到】
#      my-metadata: 自定义的元数据，key/value可以随便写
  client:
    serviceUrl:
#      defaultZone: http://root:1@peer1:9001/eureka,http://root:1@peer2:9002/eureka
      defaultZone: http://root:1@peer1:9001/eureka